cache:
  - .git
  - vendor

stages:
  Prepare:
    Install composer dependencies:
      docker:
        www:
          image: composer/composer
          volumes:
            - ".:/app:rw"
      commands:
        - composer install --no-scripts

  Test:
    Unit tests PHP:
      docker:
        www:
          image: trivago/rumi:php-dev-latest
          volumes:
            - ".:/var/www/html:rw"
      commands:
        - cd /var/www/html && vendor/bin/phpunit
