#!/usr/bin/env php
<?php
// application.php
set_time_limit(0);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Config\FileLocator;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Trivago\Rumi\Commands\CacheRestoreCommand;
use Trivago\Rumi\Commands\CacheStoreCommand;
use Trivago\Rumi\Commands\CheckoutCommand;
use Trivago\Rumi\Commands\RunCommand;
use Trivago\Rumi\Plugins\CouchDB\CouchDbPlugin;

$container = prepareContainer();
$eventDispatcher = new EventDispatcher();
$application = new Application();

$input = new ArgvInput();
$output = new ConsoleOutput();

loadPlugins($input, $output, $application, $container, $eventDispatcher);

$oRunCommand = new RunCommand($container, $eventDispatcher);
$application->add($oRunCommand);
$application->add(new CheckoutCommand($container));
$application->add(new CacheStoreCommand($container));
$application->add(new CacheRestoreCommand($container));
$application->setDefaultCommand($oRunCommand->getName());
$application->run($input, $output);

/**
 * @return ContainerBuilder
 */
function prepareContainer()
{
    $container = new ContainerBuilder();
    $loader = new XmlFileLoader($container, new FileLocator(__DIR__));
    $loader->load('src/Resources/config/services.xml');

    return $container;
}

function loadPlugins(
    InputInterface $input,
    OutputInterface $output,
    Application $application,
    ContainerInterface $container,
    EventDispatcherInterface $eventDispatcher)
{
    new CouchDbPlugin($input, $output, $application, $container, $eventDispatcher);
}
