FROM    trivago/rumi:php-latest

RUN  echo "@testing http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/edge/testing" > /etc/apk/repositories && apk add --update php-xdebug@testing && rm /var/cache/apk/* && echo "zend_extension=xdebug.so" > /etc/php/conf.d/xdebug.ini